### ISSUE TITLE
Introduce type-safety with TypeScript

### ISSUE THREAD

**Issue by adejolx** [azlibdar/react-customs#5]
I'm impressed with the initiative you've taken with these utilities. I'd like to propose an introduction of typescript with no intention to modify the current APIs. I can create a PR for this within the week should you find it acceptable.

Cheers.

**Comment by azlibdar** [comment]
I really appreciate your offer to help with this.

I haven't touch TypeScript yet, but I plan to soon. If we move everything to TypeScript now, it might be tricky for me to keep up and continue developing new hooks.

However, I do see the benefits of TypeScript and definitely plan to use it in the future. I'll keep you updated on my progress, and we can revisit this idea when I'm more comfortable with it.

In the meantime, if you could contribute using JavaScript, that would be great and very helpful!

Thanks again for your understanding and support!

Cheers,
Azlan Ibrahim

**Comment by adejolx** [comment]
Yes, I understand and appreciate your feedback, I'll be sure to contribute where I can. Thanks again and well done!

**Comment by azlibdar** [comment]
Sure. Thanks
